todo.md
=> Update todo list

js/courseCatalog.js
I think 3 is a good number to prefetch
=> fixes #23 - next page prefetching

js/courseCatalog.js, js/import.js
see diff
was previously throwing javascript error that prevented the buttons from initializing correctly
=> fixed "Add to UT R+" button

js/background.js, js/import.js, js/util.js
Fixes a scheduling issue where class periods falling at the same time on different days in different buildings are not differentiated by building.
=> Similar schedule fix

README.md, src/background/background.ts, src/background/events/onInstall.ts, src/background/events/onUpdate.ts, src/background/handler/hotReloadingHandler.ts, src/background/lib/addCourse.ts, src/background/lib/removeCourse.ts, src/background/util/hotReloadTab.ts, src/background/util/openDebugTab.ts, src/debug/index.tsx, src/shared/storage/UserScheduleStore.ts, src/views/hooks/useUserSchedules.ts
Fix #44
Also cleaned up README.md
=> fix: #44 Module Not Found Error

js/config.js
It was that time of the year again for course registration and I saw some quirky comments appearing every time I clicked on the app icon 
Thus I gave a shot at adding a few of my own!
=> A few more funny comments

src/shared/util/icons.tsx
Create helper function, takes in Status & classname --> returns corresponding Icon Component with classname applied
=> feat: Create icon helper

.github/workflows/chromatic.yml
- ci: chromatic builds
- hotfix: add pnpm install to workflow
- hotfix: add pnpm version
- ci: update pnpm action
=> ci: update pnpm action

src/views/hooks/useFlattenedCourseSchedule.ts
first by dayIndex, then startIndex, then endIndex.
=> fix: sort the flattened course schedule

.github/workflows/chromatic.yml
fix: change Chromatic action to build current branch
=> fix: Chromatic action to build from correct branch

src/views/hooks/useSchedules.ts
Fixes an issue in the storybook where the calendar component won't load because of UserScheduleStore being undefined
=> fix: calendar storybook issue

src/views/components/CourseCatalogMain.tsx, src/views/components/injected/TableRow/TableRow.module.scss, src/views/components/injected/TableRow/TableRow.tsx
Fixed the implementation of the ConflictsWithWarning to not look like doo doo, it was not even close before. Also commented out 1 line in CourseCatalogMain to avoid making the course titles look so big.
=> fix: conflict row bug

.editorconfig, src/pages/popup/index.html, src/stories/components/PopupMain.stories.tsx, src/views/components/PopupMain.tsx, src/views/components/common/ExtensionRoot/ExtensionRoot.module.scss, src/views/components/common/ScheduleDropdown/ScheduleDropdown.tsx, src/views/hooks/useSchedules.ts, unocss.config.ts
=> refactor(popup): match styles/reduce paint flicker

src/pages/background/lib/addCourse.ts, src/pages/background/lib/clearCourses.ts, src/pages/background/lib/createSchedule.ts, src/pages/background/lib/removeCourse.ts, src/pages/background/lib/renameSchedule.ts, src/pages/background/lib/switchSchedule.ts, src/shared/storage/UserScheduleStore.ts, src/shared/types/UserSchedule.ts, src/stories/components/calendar/CalendarSchedules.stories.tsx, src/stories/injected/CourseCatalogInjectedPopup.stories.ts, src/stories/injected/mocked.ts, src/views/components/PopupMain.tsx, src/views/components/calendar/CalendarHeader/CalenderHeader.tsx, src/views/components/common/ScheduleTotalHoursAndCourses/ScheduleTotalHoursAndCourses.tsx, src/views/hooks/useFlattenedCourseSchedule.ts, src/views/lib/getUpdatedAtDateTimeString.ts
main focuses:
- Alignment of the waitlisted/closed/cancelled icons (and everything to the right of that) to be right-aligned
- Show the proper name of schedules, # of hours, # of courses, and last updated date/time
before:
after:
=> feat: calendar header formatting and data displaying

src/views/components/common/Chip/Chip.tsx, src/views/components/common/Dialog/Dialog.tsx, src/views/components/common/Text/Text.module.scss, src/views/components/injected/CourseCatalogInjectedPopup/CourseCatalogInjectedPopup.tsx, src/views/components/injected/CourseCatalogInjectedPopup/Description.tsx, src/views/components/injected/CourseCatalogInjectedPopup/GradeDistribution.tsx, src/views/components/injected/CourseCatalogInjectedPopup/HeadingAndActions.tsx
- **refactor: dialog animation improvements**
- **refactor: update ccpopup to match designs**
=> refactor: ccpopup

src/views/components/calendar/CalendarGrid/CalendarGrid.tsx
=> fix: clean up #173

src/views/components/calendar/Calendar/Calendar.tsx
The calendar comment for some reason copied the exact same text as the Chip jsdoc so I changed it to a more accurate one. Hope that helps!
=> fix: idk why that comment was there

src/shared/types/MIMEType.ts, src/shared/util/downloadBlob.ts, src/views/components/calendar/utils.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Longhorn-Developers/UT-Registration-Plus/186)
=> feat: use downloadBlob util

src/views/components/common/List.tsx
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Longhorn-Developers/UT-Registration-Plus/188)
=> fix: reactivity

src/views/components/common/ConflictsWithWarning.tsx
Bolded the course names ^
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Longhorn-Developers/UT-Registration-Plus/190)
=> refactor: updated styling of conflict component to match figma

src/views/components/common/Chip.tsx
added flag
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Longhorn-Developers/UT-Registration-Plus/195)
=> feat: added flag ;-;

src/stories/components/DialogProvider.stories.tsx, src/tsconfig.json, src/views/components/common/Dialog.tsx, src/views/components/common/DialogProvider/DialogProvider.tsx, src/views/contexts/DialogContext.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Longhorn-Developers/UT-Registration-Plus/198)
=> feat: DialogProvider component

.github/workflows/best-practices.yml, .github/workflows/check-types.yml, .github/workflows/chromatic.yml, .github/workflows/tests.yml, pnpm-lock.yaml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Longhorn-Developers/UT-Registration-Plus/213)
=> build: update pnpm version to 9

package.json, pnpm-lock.yaml, src/views/components/common/Dialog.tsx, src/views/components/common/DialogProvider/DialogProvider.tsx, src/views/components/common/Prompt.tsx, src/views/components/common/ScheduleDropdown.tsx, src/views/contexts/DialogContext.ts, unocss.config.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Longhorn-Developers/UT-Registration-Plus/212)
=> chore: update headlessui

src/views/components/common/ExtensionRoot/ExtensionRoot.module.scss, src/views/components/common/PopupCourseBlock.tsx
Somehow, the drags get "lost" within a button element. Converting the parent container to a div works to fix this.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Longhorn-Developers/UT-Registration-Plus/216)
=> fix: Fix popup drag hitbox

src/views/components/injected/CourseCatalogInjectedPopup/GradeDistribution.tsx, src/views/components/injected/CourseCatalogInjectedPopup/HeadingAndActions.tsx
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Longhorn-Developers/UT-Registration-Plus/218)
=> style: fix injected popup top/bottom padding

src/stories/components/Dropdown.stories.tsx, src/stories/components/List.stories.tsx, src/stories/components/ScheduleListItem.stories.tsx, src/stories/injected/CourseCatalogInjectedPopup.stories.tsx, src/views/components/calendar/Calendar.tsx, src/views/components/calendar/CalendarFooter.tsx, src/views/components/calendar/CalenderHeader.tsx, src/views/components/common/ExtensionRoot/ExtensionRoot.module.scss
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Longhorn-Developers/UT-Registration-Plus/215)
=> style: always show scrollbar

src/views/components/calendar/CalendarFooter.tsx, src/views/components/calendar/TeamLinks.tsx, src/views/components/injected/RecruitmentBanner/RecruitmentBanner.tsx
fixes https://github.com/orgs/Longhorn-Developers/projects/4/views/1?pane=issue&itemId=57627329 and https://github.com/orgs/Longhorn-Developers/projects/4/views/1?pane=issue&itemId=57928559
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Longhorn-Developers/UT-Registration-Plus/219)
=> feat: updated calendar page and recruitment banner links

src/views/components/calendar/Calendar.tsx, src/views/components/injected/CourseCatalogInjectedPopup/HeadingAndActions.tsx, src/views/contexts/CalendarContext.ts
old
new
changes only happen on the calendar page
resolves https://github.com/orgs/Longhorn-Developers/projects/4/views/1?filterQuery=-status%3ADone+assignee%3ASamathingamajig&pane=issue&itemId=57507370
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Longhorn-Developers/UT-Registration-Plus/221)
=> feat: popout icon for ccip in calendar

src/views/lib/CourseCatalogScraper.ts
Fixes https://github.com/orgs/Longhorn-Developers/projects/4/views/11?sliceBy%5Bvalue%5D=Razboy20&pane=issue&itemId=63758761
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Longhorn-Developers/UT-Registration-Plus/222)
=> refactor: Update getCreditHours function to handle additional cases

src/views/components/calendar/CalendarCourseCell.tsx
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Longhorn-Developers/UT-Registration-Plus/217)
=> style: add slight shadow on hover to calendar course cells

src/views/components/injected/CourseCatalogInjectedPopup/HeadingAndActions.tsx
#https://github.com/orgs/Longhorn-Developers/projects/4/views/1?pane=issue&itemId=57508375
@IsaDavRod
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Longhorn-Developers/UT-Registration-Plus/211)
=> feat: rerouted directory to syllabus when click on professor name

src/views/components/calendar/CalendarCourseCell.tsx
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Longhorn-Developers/UT-Registration-Plus/235)
=> feat: one single exclamation mark did all that

src/views/components/calendar/CalendarCourseCell.tsx
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Longhorn-Developers/UT-Registration-Plus/236)
=> feat: temporary removal of icon

src/shared/util/experimental.ts, src/views/components/PopupMain.tsx, src/views/components/calendar/CalendarCourseCell.tsx, src/views/components/calendar/CalenderHeader.tsx
icon toggle that is false for now as requested
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Longhorn-Developers/UT-Registration-Plus/237)
=> feat: experimental toggle for icons, left off for now

src/shared/types/CourseMeeting.ts, src/views/components/injected/CourseCatalogInjectedPopup/HeadingAndActions.tsx
Added room number to injected course popup
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Longhorn-Developers/UT-Registration-Plus/231)
=> fix: added room number to course popup

pnpm-lock.yaml, src/views/components/PopupMain.tsx, src/views/components/calendar/CalenderHeader.tsx
ok hooked it up to our refresh config option thing
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Longhorn-Developers/UT-Registration-Plus/239)
=> feat: Derek/disable updating

src/views/components/common/List.tsx
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Longhorn-Developers/UT-Registration-Plus/240)
=> fix: improper list data propagation

README.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Longhorn-Developers/UT-Registration-Plus/241)
=> docs: update readme for UTRP v2 prod release

src/shared/types/CourseSchedule.ts
after:
before:
note: these changes only apply for classes that are re-scraped, since this PR only modifies code around the scraper
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Longhorn-Developers/UT-Registration-Plus/242)
=> fix: support classes with no location

src/pages/background/lib/deleteSchedule.ts, src/views/components/common/Prompt.tsx, src/views/components/common/ScheduleListItem.tsx, src/views/components/injected/RecruitmentBanner/RecruitmentBanner.tsx
- in deleteSchedule.ts, update the logic to handle the case where the activeIndex in storage is out of the bounds of the newly truncated schedule. 
- In deleteSchedule.ts, improve the error message when trying to delete the active schedule. Instead of a generic error message, provide a more specific message instructing the user to switch to another schedule before deleting.
- 
- In Prompt.tsx, update the Prompt component to use the new DialogPanel and DialogTitle components from the @headlessui/react library.
- In ScheduleListItem.tsx, add error handling for the deleteSchedule function. If an error occurs during deletion, display a prompt dialog with the error message.
- In RecruitmentBanner.tsx, add 'DES' to the list of departments for recruitment.
- - -
This change is [<img …
=> refactor: improve error message and handle active schedule deletion

src/views/components/PopupMain.tsx
oh gahd it's 4:52 in the morning i need rest
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Longhorn-Developers/UT-Registration-Plus/255)
=> style: getting our minecraft splash text the way we need

.eslintrc.cjs, src/pages/calendar/CalendarMain.tsx, src/views/components/PopupMain.tsx, src/views/components/common/DialogProvider/DialogProvider.tsx, src/views/components/common/ScheduleListItem.tsx, src/views/contexts/DialogContext.ts
Fixes #252.
https://github.com/user-attachments/assets/6ddfa6c4-0d1d-4b39-b6cd-bb73ba0c4eba
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Longhorn-Developers/UT-Registration-Plus/257)
=> fix: improve dialog handling and error management in list items

src/views/lib/database/queryDistribution.ts
now:
prev:
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Longhorn-Developers/UT-Registration-Plus/269)
=> fix: grade dist when no instructor

src/shared/util/string.ts, src/views/components/calendar/CalendarCourseCell.tsx, src/views/hooks/useFlattenedCourseSchedule.ts
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Longhorn-Developers/UT-Registration-Plus/268)
=> feat: lowercase instructor! 

src/views/components/injected/AutoLoad/AutoLoad.tsx, src/views/components/injected/CourseCatalogInjectedPopup/Description.tsx, src/views/components/injected/CourseCatalogInjectedPopup/GradeDistribution.tsx
Completely unused imports and args
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Longhorn-Developers/UT-Registration-Plus/271)
=> chore: remove unused imports and args

package.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Longhorn-Developers/UT-Registration-Plus/280)
=> build: add pnpm run build:watch

README.md
lil animation gif demonstrating our software and bringing life to the bare readme!
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Longhorn-Developers/UT-Registration-Plus/281)
=> feat: readme animation

src/views/components/calendar/CalendarBottomBar.tsx, src/views/components/calendar/CalendarCourseCell.tsx, src/views/components/common/ScheduleListItem.tsx, src/views/hooks/useFlattenedCourseSchedule.ts
Courses on Saturday and before 8 AM will be put into the async category now!!!
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Longhorn-Developers/UT-Registration-Plus/273)
=> feat: async course adding and async/other course block adjustments

src/pages/background/util/openNewTab.ts, src/shared/types/MIMEType.ts, src/shared/types/ThemeColors.ts, src/shared/util/colors.ts, src/views/components/common/Chip.tsx, src/views/components/common/Dialog.tsx, src/views/components/common/DialogProvider/DialogProvider.tsx
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Longhorn-Developers/UT-Registration-Plus/275)
=> chore: add js-doc

src/views/components/settings/Settings.tsx, src/views/lib/getGitHubStats.ts
---
<sub><a href="https://huly.app/guest/longhorndevelopers?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJsaW5rSWQiOiI2NzBlMDEzYThkY2MwMDM2MTU1YWY1MjkiLCJndWVzdCI6InRydWUiLCJlbWFpbCI6IiNndWVzdEBoYy5lbmdpbmVlcmluZyIsIndvcmtzcGFjZSI6InctZ2l0aHVicmF6Ym95LWxvbmdob3JuZGV2ZS02NzA4NWI0ZS1kMjIzZmMxZDczLThjYzI3NiJ9.xFeZcdAdE7ulqbudxftG8YPGraPU3PBhC4Bgbijk-yM">Huly&reg;: <b>UTRP-307</b></a></sub>
=> feat: swe title updates

src/views/components/calendar/CalendarBottomBar.tsx
big yikes ugly aah dot
sigma mode; no dot
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Longhorn-Developers/UT-Registration-Plus/313)
=> style: remove ugly period after async

gulpfile.js
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Longhorn-Developers/UT-Registration-Plus/314)
=> fix(build): gulp zip

src/views/components/settings/Settings.tsx
---
<sub><a href="https://huly.app/guest/longhorndevelopers?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJsaW5rSWQiOiI2NzEwM2ZlMGNlNzQ0ODdkZDQzZDhiODIiLCJndWVzdCI6InRydWUiLCJlbWFpbCI6IiNndWVzdEBoYy5lbmdpbmVlcmluZyIsIndvcmtzcGFjZSI6InctZ2l0aHVicmF6Ym95LWxvbmdob3JuZGV2ZS02NzA4NWI0ZS1kMjIzZmMxZDczLThjYzI3NiJ9.6P-HuARXeSkplPqBGiFjQVnUElCfrdFgSiN7ZlCHHKk">Huly&reg;: <b>UTRP-312</b></a></sub>
=> fix: add a little error checking to settings

src/views/lib/getGitHubStats.ts
<sub><a href="https://huly.app/guest/longhorndevelopers?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJsaW5rSWQiOiI2NzEzMjQ5MmNlNzQ0ODdkZDQzZGZiOTAiLCJndWVzdCI6InRydWUiLCJlbWFpbCI6IiNndWVzdEBoYy5lbmdpbmVlcmluZyIsIndvcmtzcGFjZSI6InctZ2l0aHVicmF6Ym95LWxvbmdob3JuZGV2ZS02NzA4NWI0ZS1kMjIzZmMxZDczLThjYzI3NiJ9.uIIQvJ1Ca7d_dEbmXWKGbG0GXSWE_by2PJjSnsucNYs">Huly&reg;: <b>UTRP-322</b></a></sub>
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Longhorn-Developers/UT-Registration-Plus/326)
=> feat: update senior swe admins

src/views/components/calendar/CalendarBottomBar.tsx
Fixes #355
---
<sub><a href="https://huly.app/guest/longhorndevelopers?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJsaW5rSWQiOiI2NzE2ZThlNDRjMjRlYTI4ODIwMzNjMTkiLCJndWVzdCI6InRydWUiLCJlbWFpbCI6IiNndWVzdEBoYy5lbmdpbmVlcmluZyIsIndvcmtzcGFjZSI6InctZ2l0aHVicmF6Ym95LWxvbmdob3JuZGV2ZS02NzA4NWI0ZS1kMjIzZmMxZDczLThjYzI3NiJ9.MfKBzs-hUzbiAukL_EgeQxjYileM4uMZHgCta0yGxZI">Huly&reg;: <b>UTRP-350</b></a></sub>
=> fix(ui): add space before/after forward slash in "ASYNC/OTHER" text

src/views/components/calendar/ImportantLinks.tsx
Fixes #353 
added and rearranged links on calendar sidebar
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Longhorn-Developers/UT-Registration-Plus/367)
=> feat: update useful links

src/views/components/common/Text/Text.module.scss
Fixes #347.
<sub><a href="https://huly.app/guest/longhorndevelopers?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJsaW5rSWQiOiI2NzE2ZWNjMzRjMjRlYTI4ODIwMzY4NzgiLCJndWVzdCI6InRydWUiLCJlbWFpbCI6IiNndWVzdEBoYy5lbmdpbmVlcmluZyIsIndvcmtzcGFjZSI6InctZ2l0aHVicmF6Ym95LWxvbmdob3JuZGV2ZS02NzA4NWI0ZS1kMjIzZmMxZDczLThjYzI3NiJ9.RfxQAki7S9Je5CBkKgMSRNF36W7VyHVJ86QVGKrW068">Huly&reg;: <b>UTRP-354</b></a></sub>
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Longhorn-Developers/UT-Registration-Plus/370)
=> fix: changed the font-weight from 600 to 550

src/shared/types/ThemeColors.ts, src/views/components/common/MigrationDialog.tsx, src/views/components/common/ScheduleListItem.tsx, src/views/components/settings/Settings.tsx, src/views/styles/colors.module.scss
Resolves #346
<sub><a href="https://huly.app/guest/longhorndevelopers?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJsaW5rSWQiOiI2NzE3MWVkNTRjMjRlYTI4ODIwNGM4NzkiLCJndWVzdCI6InRydWUiLCJlbWFpbCI6IiNndWVzdEBoYy5lbmdpbmVlcmluZyIsIndvcmtzcGFjZSI6InctZ2l0aHVicmF6Ym95LWxvbmdob3JuZGV2ZS02NzA4NWI0ZS1kMjIzZmMxZDczLThjYzI3NiJ9.BDeX5nXtGMx_t04_2FBnzLKfZK-kXYCOgqVKWsKn7oY">Huly&reg;: <b>UTRP-361</b></a></sub>
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Longhorn-Developers/UT-Registration-Plus/377)
=> chore: One red color of #D10000

.eslintrc.cjs, src/pages/background/background.ts, src/shared/util/icons.tsx, src/views/components/PopupMain.tsx, src/views/components/calendar/CalendarGrid.tsx, src/views/components/common/Chip.tsx, src/views/components/common/Link.tsx, src/views/components/settings/Settings.tsx, src/views/lib/CourseCatalogScraper.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Longhorn-Developers/UT-Registration-Plus/385)
=> chore: fix lint warnings

src/views/components/settings/Settings.tsx
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Longhorn-Developers/UT-Registration-Plus/386)
=> fix: typo in settings page

@types/vite-env.d.ts, package.json, src/views/contexts/SentryContext.tsx, vite.config.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Longhorn-Developers/UT-Registration-Plus/389)
=> fix(build): sentry sourcemap issues

src/views/components/calendar/CalendarFooter.tsx, src/views/components/injected/CourseCatalogInjectedPopup/HeadingAndActions.tsx
Issue #338: CC popup X close button should be UT Black (#333F48) to match Figma
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Longhorn-Developers/UT-Registration-Plus/394)
=> feat(ui): changed popup close icon to #333F48

src/views/components/injected/CourseCatalogInjectedPopup/GradeDistribution.tsx
resolves #331
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Longhorn-Developers/UT-Registration-Plus/406)
=> feat: bold course number in grade distribution chart, change text to ut-black

src/views/components/injected/CourseCatalogInjectedPopup/GradeDistribution.tsx
Fixes #335.
Before:
After:
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Longhorn-Developers/UT-Registration-Plus/427)
=> fix(ui): reduce left side grade distribution margin/padding

src/shared/types/CourseMeeting.ts, src/stories/components/calendar/CalendarCourseCell.stories.tsx, src/views/components/calendar/CalendarCourseCell.tsx, src/views/components/common/Text/Text.module.scss, src/views/components/injected/CourseCatalogInjectedPopup/HeadingAndActions.tsx, src/views/hooks/useFlattenedCourseSchedule.ts
Resolves #362
BEFORE:
AFTER:
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Longhorn-Developers/UT-Registration-Plus/409)
=> feat: modify Course Block text style and time and location text

unocss.config.ts
just added an ease in for the button shadow
https://github.com/orgs/Longhorn-Developers/projects/8/views/3?pane=issue&itemId=84034998&issue=Longhorn-Developers%7CUT-Registration-Plus%7C339
for this issue ^
EDIT (Derek): 
Video demo here
https://github.com/user-attachments/assets/54ab245c-0ac9-4b6d-b0dd-e103de70d01f
<sub><a href="https://huly.app/guest/longhorndevelopers?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJsaW5rSWQiOiI2NzE4MDgxZGYwMmQ4YTAzZmIyZjgzMzgiLCJndWVzdCI6InRydWUiLCJlbWFpbCI6IiNndWVzdEBoYy5lbmdpbmVlcmluZyIsIndvcmtzcGFjZSI6InctZ2l0aHVicmF6Ym95LWxvbmdob3JuZGV2ZS02NzA4NWI0ZS1kMjIzZmMxZDczLThjYzI3NiJ9.CRnnw4AhC1z1Z5fF5JM5xYiAl2SypGZ6ZogrdxxxHCs">Huly&reg;: <b>UTRP-366</b></a></sub>
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" …
=> fix: modify shadow on-hover and animation for CC Popup filled buttons

README.md
Removed redundant line
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Longhorn-Developers/UT-Registration-Plus/439)
=> docs: remove redundant sentence in readme

src/pages/background/lib/addCourse.ts, src/pages/background/lib/importSchedule.ts, src/stories/components/FileUpload.stories.tsx, src/views/components/common/FileUpload.tsx, src/views/components/settings/Settings.tsx
that's all it does not impact anything but my work
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Longhorn-Developers/UT-Registration-Plus/447)
=> refactor: change a file name

package.json, pnpm-lock.yaml, src/shared/util/icons.tsx, src/stories/components/Button.stories.tsx, src/stories/components/DialogProvider.stories.tsx, src/stories/components/Divider.stories.tsx, src/stories/components/FileUpload.stories.tsx, src/views/components/PopupMain.tsx, src/views/components/calendar/CalendarBottomBar.tsx, src/views/components/calendar/CalendarCourseCell.tsx, src/views/components/calendar/CalendarCourseCellColorPicker/ColorPatch.tsx, src/views/components/calendar/CalendarCourseCellColorPicker/HexColorEditor.tsx, src/views/components/calendar/CalendarHeader.tsx, src/views/components/calendar/CalendarSchedules.tsx, src/views/components/calendar/ImportantLinks.tsx, src/views/components/calendar/TeamLinks.tsx, src/views/components/common/Button.tsx, src/views/components/common/FileUpload.tsx, src/views/components/common/PopupCourseBlock.tsx, src/views/components/common/ScheduleDropdown.tsx, src/views/components/common/ScheduleListItem.tsx, src/views/components/injected/CourseCatalogInjectedPopup/HeadingAndActions.tsx, src/views/components/injected/TableRow/TableRow.tsx, src/views/components/settings/Settings.tsx, src/views/hooks/useChangelog.tsx
Changed icons to phosphor icons following Isaiah's specification. Ignored social icons, the feedback icon, and the git fork icon on the settings page.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Longhorn-Developers/UT-Registration-Plus/469)
=> feat(ui): change icons to phosphor-icons #467

src/views/components/settings/Settings.tsx
Remove "hello" from "I Understand" button
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Longhorn-Developers/UT-Registration-Plus/476)
=> chore: remove typo

src/pages/background/lib/deleteSchedule.ts, src/stories/components/Button.stories.tsx, src/stories/components/FileUpload.stories.tsx, src/stories/components/Prompt.stories.tsx, src/views/components/PopupMain.tsx, src/views/components/calendar/CalendarBottomBar.tsx, src/views/components/calendar/CalendarHeader.tsx, src/views/components/calendar/CalendarSchedules.tsx, src/views/components/common/Button.tsx, src/views/components/common/FileUpload.tsx, src/views/components/common/MigrationDialog.tsx, src/views/components/common/ScheduleListItem.tsx, src/views/components/injected/CourseCatalogInjectedPopup/HeadingAndActions.tsx, src/views/components/settings/Settings.tsx, src/views/hooks/useChangelog.tsx, unocss.config.ts
Modified button variants and replaced "single" with "minimal"
Before:
After:
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Longhorn-Developers/UT-Registration-Plus/482)
=> feat(ui): update button variants following figma

README.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Longhorn-Developers/UT-Registration-Plus/487)
=> docs: add repobeats and star history

src/views/components/CourseCatalogMain.tsx
Resolves #442 
https://github.com/user-attachments/assets/79b98aa5-c973-4e8e-9fd7-df39192310a5
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Longhorn-Developers/UT-Registration-Plus/489)
=> feat(settings): allow disabling of auto-loading courses

src/views/components/common/ScheduleListItem.tsx
Before: 
After: 
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Longhorn-Developers/UT-Registration-Plus/500)
=> feat(ui): add schedule list icons

src/views/components/common/ScheduleListItem.tsx, utils/plugins/vite-build-logger.ts, vite.config.ts
Closes #493
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Longhorn-Developers/UT-Registration-Plus/507)
=> feat(build): add vite-build-logger

src/views/components/calendar/CalendarBottomBar.tsx
Fixes #517 
**Before: **
**After: **
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Longhorn-Developers/UT-Registration-Plus/538)
=> chore: rename unscheduled text at calendar footer

.github/workflows/best-practices.yml, .github/workflows/check-types.yml, .github/workflows/chromatic.yml, .github/workflows/tests.yml, Dockerfile, package.json, pnpm-lock.yaml, src/views/components/calendar/ResourceLinks.tsx
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Longhorn-Developers/UT-Registration-Plus/536)
=> chore: update lock file and set engine to use pnpm v10

package.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Longhorn-Developers/UT-Registration-Plus/540)
=> chore: use volta to pin node@20.9.0

src/views/components/common/ScheduleListItem.tsx
Resolves #527
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Longhorn-Developers/UT-Registration-Plus/546)
=> style: update delete schedule prompt

src/views/components/calendar/CalendarCourseCellColorPicker/HexColorEditor.tsx, src/views/components/calendar/DiningAppPromo.tsx, src/views/components/common/WhatsNewPopup.tsx, src/views/components/injected/AddAllButton.tsx, src/views/hooks/useWhatsNew.tsx
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Longhorn-Developers/UT-Registration-Plus/609)
=> fix: fix or ignore various eslint warning

src/pages/content/index.tsx, src/views/components/injected/SearchResultShader.tsx, src/views/components/settings/Settings.tsx, src/views/lib/getSiteSupport.ts
See #586 
Work in progress, just putting this up at 5 am before bedtime woo!
EDIT: Got it working
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Longhorn-Developers/UT-Registration-Plus/617)
=> feat: search result shading
