README.md
The original URL cannot be used to add the Extension to the browser. See the screenshots for the differences (account is masked):
=> Update Chrome Web Store Link

js/calendar.js
In the weekly calendar, clicking on the classroom location would lead you to a broken URL because of duplication. URL is no longer duplicated!
=> Fix to broken map link in calendar

js/options.js
If the contributor has their name on their github profile, it is displayed and bolded with the username underneath. If they don't have their name on their profile, their username is put in place of it and bolded.
=> Names are now displayed correctly in options page

js/calendar.js
The takePicture function would cut off the image. This is because some devices have high DPI resulting in a zoom making the width and height for the screenshot inaccurate. 
Cutoff Screenshot
Screenshot after accounting for device DPI
=> Fixes cutoff PNGs. Exporting as PNG accounts for device DPI. 

package.json, pnpm-lock.yaml, vite.config.ts
Documentation: https://github.com/unplugin/unplugin-icons
Use `ic` prefix for material icons. 
Browse https://icones.js.org/collection/ic for icon collections; if you click on an icon, you can click on the "Unplugin Icons" button to copy an import for the component quickly.
=> feat: Icon library integration

src/shared/util/colors.ts, src/shared/util/storybook.ts, src/stories/components/List.stories.tsx, src/stories/components/PopupCourseBlock.stories.tsx, src/views/components/PopupMain.tsx
switched to using material symbol icons
the old version relied on Fa icons that we no longer use, so I replaced it with references to our material symbol icons
also went ahead and converted styling to tailwind
=> feat: fix icons on PopupMain and convert to tailwind

src/views/components/CourseCatalogMain.tsx, src/views/components/calendar/CalendarCourseCell/CalendarCourseCell.tsx, src/views/components/common/CourseStatus/CourseStatus.tsx, src/views/components/injected/AutoLoad/AutoLoad.tsx, src/views/lib/CourseCatalogScraper.ts
I replaced Status with StatusType, AutoLoadStatus with AutoLoadStatusType, and I added "typeof" in front of SiteSupport to fix another type error. Not too sure about that last one, I couldn't get it to work with SiteSupportType since we specifically want either of the 2 options.
=> fix: type issues by using correct import

src/pages/background/events/onServiceWorkerAlive.ts, src/pages/background/handler/tabManagementHandler.ts, src/pages/background/handler/userScheduleHandler.ts, src/pages/popup/index.tsx, src/shared/types/Instructor.ts, src/shared/util/storybook.ts, src/shared/util/tests/colors.test.ts, src/shared/util/tests/random.test.ts, src/shared/util/tests/string.test.ts, src/shared/util/tests/themeColors.test.ts, src/shared/util/tests/time.test.ts, src/views/components/calendar/Calendar/Calendar.tsx, src/views/components/calendar/CalendarBottomBar/CalendarBottomBar.tsx, src/views/components/calendar/CalendarGrid/CalendarGrid.tsx, src/views/components/calendar/CalendarHeader/CalenderHeader.tsx, src/views/components/calendar/ImportantLinks.tsx, src/views/components/common/Button/Button.tsx, src/views/components/common/Chip/Chip.tsx, src/views/components/common/ConflictsWithWarning/ConflictsWithWarning.tsx, src/views/components/common/CourseStatus/CourseStatus.tsx, src/views/components/common/InfoCard/InfoCard.tsx, src/views/components/common/Link/Link.tsx, src/views/components/common/PopupCourseBlock/PopupCourseBlock.tsx, src/views/components/common/ScheduleTotalHoursAndCourses/ScheduleTotalHoursAndCourses.tsx, src/views/components/injected/CoursePopupOld/CoursePopup.tsx, src/views/components/injected/RecruitmentBanner/RecruitmentBanner.tsx, src/views/components/injected/TableRow/TableRow.tsx, utils/plugins/make-manifest.ts
I searched for every import that could be switched to using path aliasing - and switched it. I only left a few that I know will be fixed in a different PR or if they cannot be swapped over to path aliasing (as far as I know).
Also note: after renaming, a lot of the import ordering did move around a bit.
edit: i also fixed the eslint errors for sorting imports
=> fix: cleanup imports

src/views/components/calendar/CalendarBottomBar/CalendarBottomBar.tsx
Before:
After:
(red outline comes from storybook)
This is to reflect the Figma design
originally, dividers were not included because dividers hadn't been created yet
=> feat: dividers in calendar bottom bar

src/views/components/calendar/CalendarHeader/CalenderHeader.tsx
literally removed one style (py-15)
before:
after:
=> fix: remove extra spacing on CalendarHeader

options.html, src/manifest.ts, src/pages/options/index.html, src/views/components/PopupMain.tsx, vite.config.ts
Fix the options page not linking properly by using a symlink to trick it into building.
Alternatively we could just move options outwards from the src/pages OR not rename it at all. I don't think it's possible to both rename it in the vite config and use it's path in the manifest file
=> fix: options page

options.html, src/manifest.ts, vite.config.ts
Fix the issue of the symlink hack being non-deterministic. Instead we use a custom plugin to edit the manifest and manually set the options page link at the end of the build.
=> fix: non-determinstic options page generation

src/shared/types/UserSchedule.ts, src/views/components/PopupMain.tsx, src/views/hooks/useSchedules.ts
Fixes a course popup styling bug as well as some lag issues
=> fix: Schedule Switching Bugs

src/stories/components/Prompt.stories.tsx, src/views/components/common/Prompt/Prompt.tsx
Reusable popup prompt that takes a title, description, and button children components. Uses headless UI's `Transition` and `Dialog` components for accessibility and interactivity. Handles clicks outside the prompt, escape key, etc.
DEMO
=> feat: abhinavchadaga/reusable-popup-prompt

src/pages/background/background.ts, src/shared/util/updateBadgeText.ts, src/views/components/calendar/CalendarSchedules/CalendarSchedules.tsx, src/views/components/injected/TableRow/TableRow.tsx
This PR adds listeners to the `UserScheduleStore` so that we can update the current count within the extension icon with the number of courses in the active schedule
=> feat: update badge count when schedule changes

src/stories/components/calendar/CalendarBottomBar.stories.tsx, src/views/components/calendar/CalendarBottomBar/CalendarBottomBar.tsx, src/views/components/calendar/CalendarCourseCell/CalendarCourseCell.tsx
- feat: calendar bottom bar will not appear when the passed in courses is either undefined or has a length of 0.
- also added an "Empty" story in CalendarBottomBar's storybook to show off the changes
=> feat: async text hiding on Calendar's Bottom Bar when there are no async courses

src/views/components/calendar/CalendarBottomBar/CalendarBottomBar.tsx
before (no async classes): 
before (1 or more async classes)
(imagine on vertical line on the left lol)
after: 
discussion, read down from here: https://discord.com/channels/743636346727301172/743636347167834143/1217566097319137331
=> feat: fix save as button dividers

src/shared/types/CourseSchedule.ts
before: classes start/ending at noon (or anything 12:xx am/pm) mess up their start/end time, which can also mess up how conflicts are handled
(see the first instance of "endTime", should be 12 * 60 === 720, but an extra 12 hours is added)
(this shouldn't be conflicting with a 10am-12pm class)
after: corrected
=> fix: correct parsing of noon

src/views/components/common/PopupCourseBlock/PopupCourseBlock.tsx, src/views/components/injected/CourseCatalogInjectedPopup/HeadingAndActions.tsx
Pads unique numbers to 5 digits, both when displaying and when copying
Unique's need to be 5 digits, searching by the 4-digit version yields the error "Unique number needs to be 5 digits."
Before:
After:
=> feat: pad unique ids to 5 digits

.gitignore
Running `pnpm build-storybook` makes a folder called storybook-static, it shouldn't ever be committed
=> chore: ignore storybook build

src/views/components/common/Chip/Chip.tsx, src/views/components/injected/CourseCatalogInjectedPopup/HeadingAndActions.tsx
Added tooltips for course flags that show when you hover on the flag Chip! 
I can't actually get any images because tooltips don't get captured in images on Windows, but supposedly if you hovered over this "QR" it would say "Quantitative Reasoning", which is really convenient and doesn't cover up anything. 
I stumbled upon this when I was playtesting our build by pretending to be a normal student, and when I was hovering over flags to see what their full name was, nothing would pop up; so here we go
=> feat: Course Flag Tooltips

src/views/components/calendar/CalendarCourseCell/CalendarCourseCell.tsx
before (ew, so wide):
after:
I narrowed it down to a one-line change in #172:
=> fix: async course display size

src/pages/calendar/CalendarMain.tsx, src/views/components/common/ExtensionRoot/ExtensionRoot.tsx
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Longhorn-Developers/UT-Registration-Plus/185)
=> refactor: move getTabInfo to calendar only

src/views/components/common/Chip.tsx
previously, the extension would crash when opening a course that had a cultural diversity flag
example: https://utdirect.utexas.edu/apps/registrar/course_schedule/20249/30395/
Co-authored-by: Som Gupta <78577376+knownotunknown@users.noreply.github.com>
- - -
This change is not [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Longhorn-Developers/UT-Registration-Plus/196)
=> fix: don't crash on cultural diversity flag

src/views/lib/database/queryDistribution.ts
This was originally part of #191, then wasn't included when it was kinda weirdly manually merged into #163
Anyways, this PR just kinda copies over the logic from the aggregate part so that, when looking at individual semesters, it properly sums all the sections that happened during that semester instead of just the first one.
Before: C S 314 Grades Spring 2023
After: C S 314 Grades Spring 2023 (same thing)
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Longhorn-Developers/UT-Registration-Plus/202)
=> fix: Sum courses for same semester but different unique

src/stories/components/calendar/CalendarBottomBar.stories.tsx, src/stories/components/calendar/CalendarGrid.stories.tsx, src/views/components/calendar/Calendar.tsx, src/views/components/calendar/CalendarBottomBar.tsx, src/views/components/calendar/CalendarGrid.tsx, src/views/hooks/useFlattenedCourseSchedule.ts
previously, async courses were rendering in the grid
now they render in the proper place
- - -
This change may or may not be [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Longhorn-Developers/UT-Registration-Plus/204)
=> feat: show async courses in the bottom bar

package.json, pnpm-lock.yaml, src/views/components/calendar/CalendarFooter.tsx
old (yuck)
new (yum)
why?
also, in my professional opinion (and the opinion of my roommate), _none_ of the discord icons that are outlines look right.
---
I'm 99% sure this PR is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Longhorn-Developers/UT-Registration-Plus/205) but it might not be
=> feat: better discord icon

src/shared/types/ThemeColors.ts, src/views/components/PopupMain.tsx, src/views/components/calendar/CalenderHeader.tsx, src/views/components/common/LogoIcon.tsx
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Longhorn-Developers/UT-Registration-Plus/201)
=> feat: some small changes for colors and font

src/views/components/injected/CourseCatalogInjectedPopup/HeadingAndActions.tsx
Remove the course name and add the instructor first and last name to the lookup. Opens a new tab for each instructor in the list of instructors.
**Single professor**
**Multiple professors**
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Longhorn-Developers/UT-Registration-Plus/200)
=> fix: remove course name from the syllabi lookup

src/views/components/injected/CourseCatalogInjectedPopup/Description.tsx
before (yuck 🤮)
after (yummy 😋)
for https://github.com/orgs/Longhorn-Developers/projects/4/views/1?filterQuery=-status%3ADone+assignee%3ASamathingamajig&pane=issue&itemId=57505946
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Longhorn-Developers/UT-Registration-Plus/220)
=> feat: bold red refresh error

src/shared/types/Distribution.ts, src/views/components/injected/CourseCatalogInjectedPopup/GradeDistribution.tsx, src/views/lib/database/queryDistribution.ts
try to get a class by professor last name (in addition to previous filters). if no results are returned, try without the professor name but show a warning.
example for course without professor data on aggregate
example for course without professor data on a specific semester
- - -
At this point, we don't know whether this change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Longhorn-Developers/UT-Registration-Plus/225) or not
=> feat: grades by professor

src/views/components/common/Dialog.tsx, src/views/components/common/ExtensionRoot/ExtensionRoot.module.scss, src/views/components/common/LogoIcon.tsx
Fixes dialog movement when scrollbars appear/disappear during the closing animation of a dialog. 
(also only shows our custom scrollbars in the views made by the extension, rather than everywhere.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Longhorn-Developers/UT-Registration-Plus/227)
=> fix: dialog movement

src/views/lib/database/queryDistribution.ts
previously, we were using template strings, which had issues for professors with an apostrophe in their name
now includes data up to Spring 2024 (of whatever classes have public data for Spring 2024 now)
now:
previously:
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Longhorn-Developers/UT-Registration-Plus/238)
=> feat: newer grades and parameterized queries

commitlint.config.ts, package.json, pnpm-lock.yaml, src/views/components/injected/AutoLoad/AutoLoad.tsx
This pull request adds the `react-loading-skeleton` package to the project dependencies in `package.json`. This package will be used to display loading skeletons in the AutoLoad component.
https://github.com/user-attachments/assets/c185530d-484b-49d0-ab88-d40b929202b1
Additionally, the `body-max-line-length` rule has been removed from `commitlint.config.ts`. (github copilot autogenerates commit messages >100 😂
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Longhorn-Developers/UT-Registration-Plus/244)
=> feat: add react-loading-skeleton package

src/views/components/calendar/ImportantLinks.tsx
now:
prev:
added spring '25
Isaiah also wanted to hide/remove summer
elie approved commenting out summer so we could keep the pattern in the code
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Longhorn-Developers/UT-Registration-Plus/249)
=> chore: update course schedules

src/views/components/common/ScheduleListItem.tsx
#250 
Radio button no longer squished when editing
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Longhorn-Developers/UT-Registration-Plus/251)
=> fix: visual overflow bug when editing schedule name

src/views/components/injected/CourseCatalogInjectedPopup/Description.tsx, src/views/components/injected/CourseCatalogInjectedPopup/GradeDistribution.tsx
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Longhorn-Developers/UT-Registration-Plus/267)
=> feat: add skeleton loader for course description + distribution

src/views/components/injected/AutoLoad/AutoLoad.tsx, src/views/lib/loadNextCourseCatalogPage.ts
TL;DR before we showing autoload even on singular course pages, and pages that didn't even have other pages to go to. This fixes that
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Longhorn-Developers/UT-Registration-Plus/270)
=> fix: doesn't autoload on pages that don't have pages to load

src/views/components/calendar/CalendarSchedules.tsx
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Longhorn-Developers/UT-Registration-Plus/272)
=> feat: limit schedules to 10

src/views/components/common/Dialog.tsx, src/views/components/common/DialogProvider/DialogProvider.tsx
- Previously, a [Object object] message would popup when hovering over a button in a DialogProvider component
- Now, no hover message is shown.
~~- Root cause seems to be that rendering a component with an attribute named `title` will display some sort of hover message -> https://github.com/bvaughn/react-virtualized/issues/1176~~
Edit: the issue can also be fixed by properly destructuring title. Thanks to @Razboy20 for the suggestion
https://github.com/user-attachments/assets/2008eae2-c36d-4a4d-8b8d-3ada8eb4077f
https://github.com/user-attachments/assets/a6c9a0b1-6b4c-4e0b-af19-b1fd54ee1f00
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Longhorn-Developers/UT-Registration-Plus/284)
=> fix: disabled [object Object] hover message on dialog popups

src/pages/background/lib/handleDuplicate.ts
- fix: Duplicating a schedule no longer grabs trailing spaces between a given name and its duplicate counter. `trim()` is applied to any valid regex matching for `baseName`
Normal schedule name:
Schedule name with extra space:
To reproduce this with the current build, do the following:
1. Create 3 new schedules (New Schedule, New Schedule (1), New Schedule (2) )
2. Duplicate New Schedule (1)
3. This should create a schedule called `New Schedule  (2)` but appear like `New Schedule (2)` in the list, unless editing its name
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Longhorn-Developers/UT-Registration-Plus/286)
=> fix: duplicate schedule name regex no longer grabs trailing white space

src/views/components/calendar/CalenderHeader.tsx
=> fix(ui): unhid settings button

src/stories/components/UpdateText.stories.tsx, src/views/components/common/UpdateText.tsx
derek's part to be connected to Diego's PR #292
<sub><a href="https://huly.app/guest/longhorndevelopers?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJsaW5rSWQiOiI2NzBhMDc5ZmM3ZDZhNTZhOGY5NGM2NmMiLCJndWVzdCI6InRydWUiLCJlbWFpbCI6IiNndWVzdEBoYy5lbmdpbmVlcmluZyIsIndvcmtzcGFjZSI6InctZ2l0aHVicmF6Ym95LWxvbmdob3JuZGV2ZS02NzA4NWI0ZS1kMjIzZmMxZDczLThjYzI3NiJ9.orCsOaLRdVUDwZWtQVOCI6cr7ghZuAVFSvElgLv1rjk">Huly&reg;: <b>UTRP-290</b></a></sub>
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Longhorn-Developers/UT-Registration-Plus/293)
=> feat: migration update showing

src/pages/background/handler/calendarBackgroundHandler.ts
Previously, we tried to have one global calendar page. One problem with that is that the tab could exist but might be in a window that can't be focused. When that happens, a user has no visual explanation of why the calendar refuses to open.
This PR makes the calendar page only show once per window, instead of once per browser.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Longhorn-Developers/UT-Registration-Plus/312)
=> fix: show calendar in active window

gulpfile.js, vite.config.ts
---
<sub><a href="https://huly.app/guest/longhorndevelopers?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJsaW5rSWQiOiI2NzEwODEyYmNlNzQ0ODdkZDQzZDkwMzYiLCJndWVzdCI6InRydWUiLCJlbWFpbCI6IiNndWVzdEBoYy5lbmdpbmVlcmluZyIsIndvcmtzcGFjZSI6InctZ2l0aHVicmF6Ym95LWxvbmdob3JuZGV2ZS02NzA4NWI0ZS1kMjIzZmMxZDczLThjYzI3NiJ9.YiN2kRv5WHU8FPJUKAzyDWhsjiRQusPS6fqZVmu45V4">Huly&reg;: <b>UTRP-313</b></a></sub>
=> build: sentry instrumentation

src/views/components/injected/CourseCatalogInjectedPopup/HeadingAndActions.tsx
When a course has no instructors, we can't show the CES or RateMyProfessor, but we can show course-wide syllabus data.
before:
https://github.com/user-attachments/assets/78476f88-6ce5-46a5-8a6b-ad4c27826783
after:
https://github.com/user-attachments/assets/4f6fc55a-1f6c-4848-8d4c-3a1dceb5011d
<sub><a href="https://huly.app/guest/longhorndevelopers?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJsaW5rSWQiOiI2NzExM2Y0MGNlNzQ0ODdkZDQzZGE1OWQiLCJndWVzdCI6InRydWUiLCJlbWFpbCI6IiNndWVzdEBoYy5lbmdpbmVlcmluZyIsIndvcmtzcGFjZSI6InctZ2l0aHVicmF6Ym95LWxvbmdob3JuZGV2ZS02NzA4NWI0ZS1kMjIzZmMxZDczLThjYzI3NiJ9.0RwWB2bGnV-uHPRsiUyeWOifKicDwH6gGGNaBEfYsX4">Huly&reg;: <b>UTRP-315</b></a></sub>
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" …
=> feat: disable/some actions when no instructor

src/views/components/calendar/CalendarFooter.tsx
Adds linkedin icon to the footer that links to longhorn developer linkedin page.
<sub><a href="https://huly.app/guest/longhorndevelopers?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJsaW5rSWQiOiI2NzE2ZWI4OTRjMjRlYTI4ODIwMzVhMjAiLCJndWVzdCI6InRydWUiLCJlbWFpbCI6IiNndWVzdEBoYy5lbmdpbmVlcmluZyIsIndvcmtzcGFjZSI6InctZ2l0aHVicmF6Ym95LWxvbmdob3JuZGV2ZS02NzA4NWI0ZS1kMjIzZmMxZDczLThjYzI3NiJ9.2X3SbFAoW291tBTR3Oiev6qCbjpB9TJ1p-L5dmtonDc">Huly&reg;: <b>UTRP-352</b></a></sub>
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Longhorn-Developers/UT-Registration-Plus/368)
=> feat: Add linkedin social to calendar

src/shared/types/ThemeColors.ts
Resolves #346
Changed UTRP Red within ut: { } in src>shared>types>ThemeColors.ts to #d10000
<sub><a href="https://huly.app/guest/longhorndevelopers?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJsaW5rSWQiOiI2NzE2ZWY2NTRjMjRlYTI4ODIwMzg3NjIiLCJndWVzdCI6InRydWUiLCJlbWFpbCI6IiNndWVzdEBoYy5lbmdpbmVlcmluZyIsIndvcmtzcGFjZSI6InctZ2l0aHVicmF6Ym95LWxvbmdob3JuZGV2ZS02NzA4NWI0ZS1kMjIzZmMxZDczLThjYzI3NiJ9.b4aB-RF3wusOAC99MDFMCAOPf-vQcuDjBxM9x7Ux7n8">Huly&reg;: <b>UTRP-357</b></a></sub>
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Longhorn-Developers/UT-Registration-Plus/373)
=> chore: Change color UTRP Red to #d10000

src/views/components/calendar/CalendarCourseCell.tsx
Removed padding screenshot class from calendar course cell to prevent cutoff issue for 1 hr courses
<sub><a href="https://huly.app/guest/longhorndevelopers?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJsaW5rSWQiOiI2NzE3MTk1MTRjMjRlYTI4ODIwNGM3NzkiLCJndWVzdCI6InRydWUiLCJlbWFpbCI6IiNndWVzdEBoYy5lbmdpbmVlcmluZyIsIndvcmtzcGFjZSI6InctZ2l0aHVicmF6Ym95LWxvbmdob3JuZGV2ZS02NzA4NWI0ZS1kMjIzZmMxZDczLThjYzI3NiJ9.8ezO9XgnfkoJI6qF_EkVoJBgpSEJv_vTqSIOt_ONbHk">Huly&reg;: <b>UTRP-360</b></a></sub>
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Longhorn-Developers/UT-Registration-Plus/376)
=> fix: remove screenshot padding class for png download for #344

src/shared/types/CRXPages.ts, src/views/components/calendar/TeamLinks.tsx
Resolves #354
<sub><a href="https://huly.app/guest/longhorndevelopers?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJsaW5rSWQiOiI2NzE3ZjA0M2YwMmQ4YTAzZmIyZjY3MWIiLCJndWVzdCI6InRydWUiLCJlbWFpbCI6IiNndWVzdEBoYy5lbmdpbmVlcmluZyIsIndvcmtzcGFjZSI6InctZ2l0aHVicmF6Ym95LWxvbmdob3JuZGV2ZS02NzA4NWI0ZS1kMjIzZmMxZDczLThjYzI3NiJ9.GJ1GFiMmf25X_Zf8pRMPhGWYjA5Ue01zDZw5dNsIWYc">Huly&reg;: <b>UTRP-365</b></a></sub>
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Longhorn-Developers/UT-Registration-Plus/380)
=> feat: add more relevant links to the From the Team section

src/pages/background/background.ts, src/shared/util/updateBadgeText.ts
Fixed the issue where the Main popup icon was not showing the number 0 when a schedule with 0 hours was selected.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Longhorn-Developers/UT-Registration-Plus/395)
Resolves #343
=> fix(ui): main popup now shows 0 for empty schedule

src/pages/background/lib/duplicateSchedule.ts
Resolves #358
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Longhorn-Developers/UT-Registration-Plus/397)
=> feat: use "copy of" for duplicated schedules and place them under the original schedule #358

src/views/components/injected/CourseCatalogInjectedPopup/HeadingAndActions.tsx
Resolves #400 
Previously, a course popup that did not have an instructor would simply not display anything for instructors. Now, if a course has no instructor, a message "(No instructor has been provided)" will be displayed instead.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Longhorn-Developers/UT-Registration-Plus/402)
=> fix(ui): placeholder text for no instructor course #400

src/views/components/common/PopupCourseBlock.tsx, src/views/components/injected/CourseCatalogInjectedPopup/HeadingAndActions.tsx, src/views/hooks/useFlattenedCourseSchedule.ts
This PR resolves (#342)
The issue was improper formatting of multiple instructors in course blocks in the calendar and main extension popup.
Here are the changes:
1. Instructor names in course blocks now only display last names
2. Instructor names are spaced with a semicolon in the calendar and main extension popup
Calendar Course Block after the changes:
Main Extension Popup Course Block after the changes:
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Longhorn-Developers/UT-Registration-Plus/403)
=> fix(ui): multiple instructors are formatted properly, displays last name only, and are capitalized in all course blocks (#342)

src/views/components/injected/CourseCatalogInjectedPopup/GradeDistribution.tsx
- The **Other** category in the grade distribution popup is somewhat ambiguous for the users, so I added a simple description underneath the chart to explain its meaning.
- I referenced the official [UT Course Grade Distribution](https://reports.utexas.edu/spotlight-data/ut-course-grade-distributions) to write this explanation. You can find their original explanation in the **(?)** help popup.
<sub><a href="https://huly.app/guest/longhorndevelopers?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJsaW5rSWQiOiI2NzEyNmVkN2NlNzQ0ODdkZDQzZGJhMjIiLCJndWVzdCI6InRydWUiLCJlbWFpbCI6IiNndWVzdEBoYy5lbmdpbmVlcmluZyIsIndvcmtzcGFjZSI6InctZ2l0aHVicmF6Ym95LWxvbmdob3JuZGV2ZS02NzA4NWI0ZS1kMjIzZmMxZDczLThjYzI3NiJ9.rrusc9TpTXQBSCGh3mn3tuyer4_48rSP-oaMg7VuM8Y">Huly&reg;: <b>UTRP-321</b></a></sub>
- - -
This …
=> feat: add explanation to grade distribution

src/views/components/injected/CourseCatalogInjectedPopup/GradeDistribution.tsx
Resolves #334 
changed Grade Distribution Chart x-axis ticks stroke width to match Figma
Ticks were bigger than x-axis before and I changed the tick length to 1px to fix the inconsistency of tick to x-axis sizes.
Before:
After:
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Longhorn-Developers/UT-Registration-Plus/440)
=> style(ui): changed tick marks to match x-axis

src/views/components/CourseCatalogMain.tsx, src/views/components/injected/NewSearchLink.tsx
This PR resolves issue #411.
This makes it easier to begin a new search rather than scrolling to the bottom of the page, which is frustrating, especially when autoload is enabled.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Longhorn-Developers/UT-Registration-Plus/456)
=> feat(ui): add new search link

src/views/components/common/ExtensionRoot/ExtensionRoot.module.scss, src/views/components/injected/AutoLoad/AutoLoad.module.scss
gets rid of some of the annoying `pnpm build` warning
https://sass-lang.com/documentation/breaking-changes/import/
https://sass-lang.com/documentation/at-rules/use/
https://sass-lang.com/documentation/at-rules/mixin/
https://tinytip.co/tips/scss-load-css/
after:
before:
Co-authored-by: Long Phan <75595656+Wizardbacon13@users.noreply.github.com>
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Longhorn-Developers/UT-Registration-Plus/478)
=> chore: migrate to new scss import syntax

src/shared/types/ThemeColors.ts, src/views/components/calendar/CalendarFooter.tsx, src/views/components/common/Text/Text.module.scss
Updated colors within the ThemeColors.ts file. 
The issue requested that the colors `off-white-1` and `off-white-2` be added. It's worth mentioning that there is already a theme called `offwhite`, so we may want to change these `offwhite-1` and `offwhite-2` to keep naming consistent. 
We could also change the name to `off-white` instead, but this would require us to replace the CSS variable across the project.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Longhorn-Developers/UT-Registration-Plus/473)
=> feat(ui): update theme colors #466

src/views/components/injected/CourseCatalogInjectedPopup/GradeDistribution.tsx
Fixes #404.
Updated text when an instructor is not found, changed text size to small, and removed italics.
Before:
"Instructor-specific data is not available for this course, showing course-wide data instead" 
After:
"We couldn't find instructor-specific grades, so here are the grades for all (insert course number) sections."
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Longhorn-Developers/UT-Registration-Plus/483)
=> feat(ui): change red text when instructor not found

src/views/components/injected/CourseCatalogInjectedPopup/GradeDistribution.tsx
This PR resolves issue #332.
I followed the specifications in the issue #332 to match the design as much as possible. However, AFAIK, the Highcharts API doesn't support layered box shadows and there isn't a away to control the `blur` or `spread` properly. Therefore, I only applied the first box shadow as closely as possible.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Longhorn-Developers/UT-Registration-Plus/485)
=> feat(ui): redesign grade distribution tooltip

src/pages/background/handler/calendarBackgroundHandler.ts, src/shared/storage/OptionsStore.ts, src/views/components/settings/Settings.tsx
Adds setting to always open the calendar view in a new tab when navigating to the calendar page. May prevent issues where the calendar refuses to open. Defaults to false.
https://github.com/user-attachments/assets/715b08ee-c516-437a-8901-d89038e2f760
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Longhorn-Developers/UT-Registration-Plus/488)
=> feat(settings): add option to always open calendar in new tab

src/views/components/settings/Settings.tsx
This PR resolves issue #424.
Additionally, I adjusted the settings page header to match the Figma (convert from ALL CAPS to Normal Case).
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Longhorn-Developers/UT-Registration-Plus/457)
=> feat: add open calendar button

src/views/components/calendar/CalendarHeader/CalendarHeader.tsx
Before: 
After:
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Longhorn-Developers/UT-Registration-Plus/504)
=> fix(ui): stop export button dropdown from squishing

src/pages/popup/index.html, src/shared/storage/OptionsStore.ts, src/shared/types/CourseMeeting.ts, src/stories/components/SortableList.stories.tsx, src/views/components/PopupMain.tsx, src/views/components/calendar/Calendar.tsx, src/views/components/calendar/CalendarBottomBar.tsx, src/views/components/calendar/CalendarCourseCellColorPicker/CourseCellColorPicker.tsx, src/views/components/calendar/CalendarHeader/CalendarHeader.tsx, src/views/components/common/Divider.tsx, src/views/components/common/PopupCourseBlock.tsx, src/views/components/common/ScheduleDropdown.tsx, src/views/components/common/ScheduleListItem.tsx, src/views/components/settings/Settings.tsx
Resolves #498
Before: 
After: 
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Longhorn-Developers/UT-Registration-Plus/506)
=> feat(ui): update popup and course blocks

src/views/components/calendar/ResourceLinks.tsx
This change ensures that people can easily get to the Summer and Fall '25 course catalogs when they release (typically, first week of March).
These links follow the URL pattern that UT has been using for years.
Now
Previously
Going to keep Spring '25 there until the end of the semester.
Eventually, we'll want this to be automated based on the dates.
The screen looks like this before the course catalogs get released. I thought about showing a warning before this page opens, but I think it does a pretty good job of saying "is not currently available".
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Longhorn-Developers/UT-Registration-Plus/534)
=> chore(cal): update course schedule links for fall and summer 2025

src/views/components/injected/CourseCatalogInjectedPopup/GradeDistribution.tsx
Fixes #523 
Before:
After:
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Longhorn-Developers/UT-Registration-Plus/537)
=> chore: changed text to data source

src/views/components/PopupMain.tsx
Before: swapping between multiple empty schedules shows the same splash text. It's jarring.
https://github.com/user-attachments/assets/659efd73-cb65-45b9-8d71-20bdfadebe91
After: swapping between multiple empty schedules show a new splash text every time. It's beautiful.
https://github.com/user-attachments/assets/16adf601-6c3a-45fc-99c0-a7625531036a
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Longhorn-Developers/UT-Registration-Plus/554)
=> feat: ensure unique splash text on schedule change

src/views/components/common/ScheduleDropdown.tsx
Before:
After:
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Longhorn-Developers/UT-Registration-Plus/564)
=> fix(schedule): truncate long schedule names in popup

package.json, pnpm-lock.yaml, src/shared/util/string.ts, src/shared/util/tests/string.test.ts, src/stories/injected/mocked.ts, src/views/components/calendar/academic-calendars.ts, src/views/components/calendar/utils.test.ts, src/views/components/calendar/utils.ts
Now will export classes based on the academic calendar. Allows for skipping holidays and multi-day breaks. Accounts for semesters by using the semester info on the course itself, so it's legal to have a schedule with multiple semesters (though, that should be prevented in general, but that will be a separate PR).
Resolves #451
Drawbacks: Doesn't support winter terms or any of the various summer terms, except it interprets all summer courses as full-term summer courses.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Longhorn-Developers/UT-Registration-Plus/535)
=> fix: ics calendar export dates

src/views/components/calendar/Calendar.tsx, src/views/components/calendar/CalendarGrid.tsx, src/views/components/calendar/CalendarGridCell.tsx, src/views/components/calendar/CalendarHeader/CalendarHeader.tsx, src/views/hooks/tests/useFlattenedCourseSchedule.test.ts, src/views/hooks/useFlattenedCourseSchedule.ts
before:
- Header (schedule name, hours, courses, export) scrolls away
- Table header (MON, TUE, WED, THU, FRI) scrolls away
https://github.com/user-attachments/assets/fbf36380-968b-42da-9c40-2362270bc16b
after:
- Header (schedule name, hours, courses, export) sticky, regardless of scroll
- Table header (MON, TUE, WED, THU, FRI) sticky, regardless of scroll
https://github.com/user-attachments/assets/8d0b2fea-c7dc-4f28-9a65-5ef83d297585
Resolves #357
Closes #560
Related: #486
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Longhorn-Developers/UT-Registration-Plus/568)
=> feat: sticky calendar header and days

src/shared/util/tests/time.test.ts
The existing test failed 11/100 times and 38/1000 times when ran in a loop. Additionally, at least two users have experienced this test case failing when running `pnpm test`.
This is due to JavaScript's event loop and the lack of precision around `setTimeout`.
This PR allows for one millisecond of grace period for that test. Additionally, I switched from `Date.now()` to `performance.now()` to 1. get more accurate errors if this does fail in the future, and 2. not have to deal with edge cases like a system changing its clock while the test is running.
I ran this modified test over 2,000 times and it never failed.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Longhorn-Developers/UT-Regi …
=> test: fix flaky sleep test

src/views/components/calendar/Calendar.tsx, src/views/components/calendar/CalendarHeader/CalendarHeader.tsx, src/views/components/calendar/utils.ts
Adds the logo to the top left corner of the calendar screenshot ("save as png").
Also, fixes a regression introduced inadvertently by #464 which broke screenshots on small/zoomed in windows.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Longhorn-Developers/UT-Registration-Plus/579)
=> fix: include logo in screenshot, fix screenshots on small/zoomed windows

.github/dependabot.yml
Configured dependabot to update all non-patched (i.e. not crxjs and unocss) dependencies, in two groupings:
- Minor/patches (hopefully easy to merge PR)
- Just major updates (might cause build to fail)
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Longhorn-Developers/UT-Registration-Plus/603)
=> chore: setup dependabot configuration

gulpfile.js, package.json, vite.config.ts
When a build is produced through `pnpm build`, Sentry instrumentation considers that build to be a production build, causing our sentry logs to fill up with development spam.
This should fix that, as Sentry should now consider these builds to be development builds, unless they are built with `SENTRY_ENV=production` environment variable.
To that end, I've added a new script command for when we need to actually publish a new version:
- `pnpm zip:to-public`: zips and includes/uploads Sentry instrumentation, and is given the context of production.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Longhorn-Developers/UT-Registration-Plus/604)
=> fix: hide sentry instrumentation on debug builds

src/views/components/calendar/ResourceLinks.tsx
added link to the spring 2026 course schedule (alongside the previous fall 2025 and summer 2025 that were already there)
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Longhorn-Developers/UT-Registration-Plus/628)
=> chore(ui): added spring 2026 course schedule
